import 'dart:convert';

import 'package:flutter/services.dart' show rootBundle;

/// Loads the precomputed word -> points map (assets/dictionary/words.json,
/// generated by scripts/build_dictionary.mjs) once and serves O(1) lookups.
class DictionaryRepository {
  DictionaryRepository._(this._words);

  final Map<String, int> _words;

  static DictionaryRepository? _instance;

  static Future<DictionaryRepository> load() async {
    if (_instance != null) return _instance!;
    final raw = await rootBundle.loadString('assets/dictionary/words.json');
    final decoded = jsonDecode(raw) as Map<String, dynamic>;
    final words = decoded.map((key, value) => MapEntry(key, value as int));
    _instance = DictionaryRepository._(words);
    return _instance!;
  }

  bool contains(String word) => _words.containsKey(word);

  int? pointsFor(String word) => _words[word];

  Iterable<String> get allWords => _words.keys;

  int get wordCount => _words.length;
}
